name: "CNNModel"
pretrained_model_paths: null #/cluster/project/bmds_lab/sepsis_jan/pulse/output_to_keep/results_benchmark/20250603_160304_CNN/Models
params:
  # Basic configuration
  trainer_name: "CNNTrainer"
  type: "convDL" # Type of model (convML for conventional machine learning, convDL for conventional deep learning and LLM for large language models)
  architecture_type: "CNN" # Architecture type (CNN, RNN)
  mode: "train" # Mode of operation (inference, train)
  save_checkpoint: 0 # Save checkpoint every n epochs. Set to 0 to disable.
  verbose: 2 # Controls verbosity of output (0 = silent, 1 = log every 100 batches, 2 = log every batch)

  # Model Architecture
  output_shape: 1 # binary classification
  kernel_size: [1, 3, 5] # Kernel sizes for convolutional layers
  pool_size: 2
  dropout_rate: 0.3

  # Training
  num_epochs: 100
  early_stopping_rounds: 10 # Number of rounds for early stopping

  # Optimization
  learning_rate: 0.001
  grad_clip_max_norm: 2.0 # max_norm = 1.0 (LSTM, GRU) or 2.0 (CNN, InceptionTime)

  # Scheduler
  scheduler_factor: 0.1
  scheduler_patience: 5
  scheduler_cooldown: 0
  min_lr: 0.000001 # 1e-6
