# Configuration file for pulse benchmark

# General settings
general:
  app_name: "Pulse"
  app_version: "1.0.3"
  app_mode: "benchmark" # "debug", "count_tokens", "benchmark"
  debug_data_length: 10 # Number of samples to use for debugging
  logging_level: "DEBUG" # "DEBUG", "INFO", "WARNING", "ERROR"
  use_scratch: true # Whether to use scratch space for temporary files
  save_metadata: true # Whether to save the metadata file. Inludes prompts for LLMs

# Weight and Biases (wandb) logging configuration
wandb:
  enabled: false
  entity: ""

###### Application specific settings ######
base_path: ""
original_base_path: ""

# Tasks to process
tasks:
  - "mortality"
  - "aki"
  - "sepsis"

# Datasets to process
dataset_path: "datasets/original_harmonized" #"/path/to/datasets"
datasets:
  - "eicu"
  - "hirid"
  - "miiv"

# _______ Preprocessing Baseline _______

preprocessing_baseline:
  replace_outliers: true # Whether to replace outliers with NaNs
  flag_na: true # Whether to flag NA values with binary indicators
  standardize: false # Whether to standardize features (yes: convDL, not required: convML, LLM)
  static_imputation: true # Whether to perform static feature imputation
  dynamic_imputation: true # Whether to perform dynamic feature imputation
  split_ratios: # Train/Val/Test split ratios
    train: 0.8
    val: 0.1
    test: 0.1
    test_limited: 100 # Number of stay_ids for limited test set, null = test set is not limited
    samples_per_stayid: 10 # Number of samples to keep per stay_id for aki/sepsis (null = all samples)
    print_stats: true # Whether to print set statistics

# _______ Preprocessing Advanced _______

preprocessing_advanced:
  windowing:
    enabled: true # Enable/disable windowing
    data_window: 6 # Size of the data window
    prediction_window: 0 # Size of the prediction window (0 = predict at the end of window)
    step_size: 1 # Step size for sliding windows
    save_data: true # Whether to save windowed data

# _______ Preprocessing Prompting _______

prompting:
  prompting_ids: # Only select one at a time
    - "sarvari_2024_aggregation_preprocessor"
    - "zhu_2024b_zero_shot_preprocessor" # fixed shots = 0
    - "zhu_2024b_one_shot_preprocessor" # fixed shots = 1
    - "liu_2023_few_shot_preprocessor" # determine shots below
    - "zhu_2024a_cot_preprocessor" # determine shots below
    - "zhu_2024c_categorization_summary_agent_preprocessor"
    - "collaborative_reasoning_agent_preprocessor"
    - "clinical_workflow_agent_preprocessor"
    - "hybrid_reasoning_agent_preprocessor"

  shots: 0

# _______ Model Training _______

benchmark_settings:
  batch_size: 64
  random_seed: 42

load_models:
  - "configs/model_configs/RandomForestModel.yaml"
  - "configs/model_configs/XGBoostModel.yaml"

  - "configs/model_configs/CNNModel.yaml"
  - "configs/model_configs/InceptionTimeModel.yaml"
  - "configs/model_configs/LSTMModel.yaml"
  - "configs/model_configs/GRUModel.yaml"

  - "configs/model_configs/Llama3.yaml"
  - "configs/model_configs/DeepseekR1Llama8bModel.yaml"
  - "configs/model_configs/MistralModel.yaml"
  - "configs/model_configs/Gemma34BModel.yaml"
  - "configs/model_configs/MedGemma4bModel.yaml"

  - "configs/model_configs/GPT4oModel.yaml" 
  - "configs/model_configs/OpenAIo3Model.yaml"
  - "configs/model_configs/Gemini2p5flashModel.yaml" 
  - "configs/model_configs/ClaudeSonnet4Model.yaml" 
  - "configs/model_configs/Grok4.yaml" 
